export interface City {
  slug: string
  name: string
  county: string
  lat: number
  lng: number
  population: number
  zipCodes: string[]
  neighborhoods: string[]
  description: string
}

export const CITIES: City[] = [
  {
    slug: 'lakeland',
    name: 'Lakeland',
    county: 'Polk',
    lat: 28.0395,
    lng: -81.9498,
    population: 115000,
    zipCodes: ['33801', '33803', '33805', '33809', '33810', '33811', '33812', '33813'],
    neighborhoods: ['North Lakeland', 'South Lakeland', 'Highlands', 'Lakeland Highlands', 'Combee Settlement', 'Kathleen', 'Medulla', 'Scott Lake'],
    description: 'Lakeland is the largest city in Polk County and a major hub for Central Florida. Our team serves all neighborhoods from North Lakeland to South Lakeland, Kathleen, Medulla, and everywhere in between.',
  },
  {
    slug: 'winter-haven',
    name: 'Winter Haven',
    county: 'Polk',
    lat: 28.0222,
    lng: -81.7329,
    population: 45000,
    zipCodes: ['33880', '33881', '33884'],
    neighborhoods: ['Eloise', 'Eagle Lake', 'Lake Alfred', 'Lake Hamilton', 'Dundee'],
    description: 'Winter Haven is home to beautiful chain-of-lakes and LEGOLAND Florida. We serve all of Winter Haven and surrounding Polk County communities including Eloise, Eagle Lake, and Lake Alfred.',
  },
  {
    slug: 'kissimmee',
    name: 'Kissimmee',
    county: 'Osceola',
    lat: 28.2919,
    lng: -81.4076,
    population: 80000,
    zipCodes: ['34741', '34743', '34744', '34746', '34747'],
    neighborhoods: ['Buenaventura Lakes', 'Flora Ridge', 'East Kissimmee', 'Celebration', 'Hunters Creek'],
    description: 'Kissimmee is the seat of Osceola County and a gateway to Central Florida attractions. We provide fast garage door service throughout Kissimmee including Buenaventura Lakes, Flora Ridge, and East Kissimmee.',
  },
  {
    slug: 'orlando',
    name: 'Orlando',
    county: 'Orange',
    lat: 28.5383,
    lng: -81.3792,
    population: 307000,
    zipCodes: ['32801', '32803', '32804', '32806', '32807', '32808', '32809', '32810', '32812', '32819', '32824', '32827', '32836'],
    neighborhoods: ['Dr. Phillips', 'Lake Nona', 'College Park', 'Windermere', 'MetroWest', 'Sand Lake', 'Bay Hill', 'Ocoee', 'Winter Park'],
    description: 'Orlando is the heart of Central Florida and one of the fastest-growing cities in the U.S. Our team serves all Orlando neighborhoods from Dr. Phillips and Bay Hill to Lake Nona and College Park.',
  },
  {
    slug: 'clermont',
    name: 'Clermont',
    county: 'Lake',
    lat: 28.5494,
    lng: -81.7729,
    population: 45000,
    zipCodes: ['34711', '34714', '34715'],
    neighborhoods: ['Minneola', 'Groveland', 'Mascotte', 'Lost Lake', 'Green Valley West'],
    description: 'Clermont sits in the rolling hills of Lake County and is one of Central Florida\'s fastest-growing communities. We serve all of Clermont including Minneola, Groveland, and Lost Lake.',
  },
  {
    slug: 'ocala',
    name: 'Ocala',
    county: 'Marion',
    lat: 29.1872,
    lng: -82.1401,
    population: 63000,
    zipCodes: ['34470', '34471', '34472', '34473', '34474', '34475', '34476', '34480', '34481', '34482'],
    neighborhoods: ['Silver Springs Shores', 'Marion Oaks', 'On Top of the World', 'Forest', 'Dunnellon area'],
    description: 'Ocala is the Horse Capital of the World and the center of Marion County. We provide garage door repair, installation, and emergency service throughout Ocala including Silver Springs Shores and On Top of the World.',
  },
  {
    slug: 'haines-city',
    name: 'Haines City',
    county: 'Polk',
    lat: 28.1139,
    lng: -81.6218,
    population: 27000,
    zipCodes: ['33844'],
    neighborhoods: ['Lake Hamilton', 'Dundee', 'Grenelefe', 'Highland City area'],
    description: 'Haines City is a growing Polk County community situated between Lakeland and Kissimmee. We serve all of Haines City, Lake Hamilton, Dundee, and surrounding Polk County neighborhoods.',
  },
  {
    slug: 'auburndale',
    name: 'Auburndale',
    county: 'Polk',
    lat: 28.0659,
    lng: -81.7887,
    population: 18000,
    zipCodes: ['33823'],
    neighborhoods: ['Polk City', 'Lake Alfred', 'Medulla', 'Chain of Lakes area'],
    description: 'Auburndale is a charming Polk County city nestled between Lakeland and Winter Haven. Our team provides same-day garage door service throughout Auburndale and surrounding Polk City and Lake Alfred areas.',
  },
  {
    slug: 'bartow',
    name: 'Bartow',
    county: 'Polk',
    lat: 27.8978,
    lng: -81.8432,
    population: 20000,
    zipCodes: ['33830'],
    neighborhoods: ['Homeland', 'Mulberry', 'Fort Meade area', 'Lake Garfield area'],
    description: 'Bartow is the county seat of Polk County, known for its historic district and Southern charm. We serve all of Bartow, Homeland, Mulberry, and surrounding south Polk County communities.',
  },
  {
    slug: 'plant-city',
    name: 'Plant City',
    county: 'Hillsborough',
    lat: 28.0189,
    lng: -82.1145,
    population: 40000,
    zipCodes: ['33563', '33565', '33566', '33567'],
    neighborhoods: ['Valrico', 'Lithia', 'Fish Hawk', 'Dover area'],
    description: 'Plant City is the Strawberry Capital of the World in Hillsborough County. We provide full garage door services to Plant City, Valrico, Lithia, Fish Hawk, and surrounding communities.',
  },
  {
    slug: 'brandon',
    name: 'Brandon',
    county: 'Hillsborough',
    lat: 27.9378,
    lng: -82.2859,
    population: 115000,
    zipCodes: ['33510', '33511'],
    neighborhoods: ['Valrico', 'Riverview', 'Seffner', 'FishHawk Ranch'],
    description: 'Brandon is one of the largest communities in Hillsborough County and a major suburb east of Tampa. Our team serves all of Brandon, Valrico, Riverview, Seffner, and FishHawk Ranch.',
  },
  {
    slug: 'davenport',
    name: 'Davenport',
    county: 'Polk',
    lat: 28.1611,
    lng: -81.6015,
    population: 8000,
    zipCodes: ['33837', '33896', '33897'],
    neighborhoods: ['Four Corners', 'Champions Gate', 'Loughman', 'Lake Wilson area'],
    description: 'Davenport is a rapidly growing Polk County community near the Osceola County border. We serve all of Davenport, Four Corners, Champions Gate, and Loughman.',
  },
  {
    slug: 'poinciana',
    name: 'Poinciana',
    county: 'Polk',
    lat: 28.1278,
    lng: -81.4915,
    population: 65000,
    zipCodes: ['34758', '34759'],
    neighborhoods: ['Poinciana Parkway corridor', 'Doral Pointe', 'Pleasant Hill area', 'Solivita'],
    description: 'Poinciana is one of the fastest-growing communities in Central Florida spanning both Polk and Osceola counties. We provide full garage door services throughout Poinciana including Solivita and Doral Pointe.',
  },
  {
    slug: 'st-cloud',
    name: 'St. Cloud',
    county: 'Osceola',
    lat: 28.2489,
    lng: -81.2812,
    population: 55000,
    zipCodes: ['34769', '34771', '34772', '34773'],
    neighborhoods: ['Narcoossee', 'Harmony', 'St. Cloud Lakefront', 'NovaStar', 'East Lake Toho area'],
    description: 'St. Cloud is a growing Osceola County city just southeast of Kissimmee. We serve all of St. Cloud including Narcoossee, Harmony, and East Lake Tohopekaliga communities.',
  },
  {
    slug: 'celebration',
    name: 'Celebration',
    county: 'Osceola',
    lat: 28.3239,
    lng: -81.5478,
    population: 11000,
    zipCodes: ['34747'],
    neighborhoods: ['North Village', 'East Village', 'South Village', 'West Village', 'Artisan Park'],
    description: 'Celebration is a master-planned community in Osceola County developed near Walt Disney World. We provide expert garage door service to all Celebration villages including North Village, East Village, and Artisan Park.',
  },
  {
    slug: 'champions-gate',
    name: 'Champions Gate',
    county: 'Osceola',
    lat: 28.2556,
    lng: -81.5901,
    population: 4000,
    zipCodes: ['33896'],
    neighborhoods: ['Davenport corridor', 'Reunion resort area', 'Providence community'],
    description: 'Champions Gate is a master-planned resort and residential community near Davenport in Osceola County. We serve Champions Gate and all surrounding resort and residential communities.',
  },
  {
    slug: 'reunion',
    name: 'Reunion',
    county: 'Osceola',
    lat: 28.2292,
    lng: -81.5942,
    population: 3000,
    zipCodes: ['34747'],
    neighborhoods: ['Traditions', 'Liberty Bluff', 'Muirfield Village', 'Champions Gate adjacent'],
    description: 'Reunion is an exclusive resort and residential community in Osceola County adjacent to Champions Gate. We serve all Reunion neighborhoods and surrounding Osceola County communities.',
  },
  {
    slug: 'deltona',
    name: 'Deltona',
    county: 'Volusia',
    lat: 28.9005,
    lng: -81.2637,
    population: 92000,
    zipCodes: ['32725', '32738', '32739'],
    neighborhoods: ['Orange City', 'DeBary', 'Deltona Lakes', 'Enterprise', 'Lake Helen area'],
    description: 'Deltona is the largest city in Volusia County and a fast-growing community north of Orlando. We serve all of Deltona including Orange City, DeBary, Deltona Lakes, and Enterprise.',
  },
  {
    slug: 'sanford',
    name: 'Sanford',
    county: 'Seminole',
    lat: 28.8006,
    lng: -81.2731,
    population: 62000,
    zipCodes: ['32771', '32773'],
    neighborhoods: ['Lake Mary', 'Heathrow', 'Midway', 'Goldsboro', 'Geneva area'],
    description: 'Sanford is the county seat of Seminole County with a vibrant historic downtown on Lake Monroe. We provide garage door services throughout Sanford, Lake Mary, Heathrow, and all of Seminole County.',
  },
  {
    slug: 'apopka',
    name: 'Apopka',
    county: 'Orange',
    lat: 28.6753,
    lng: -81.5323,
    population: 54000,
    zipCodes: ['32703', '32712'],
    neighborhoods: ['Zellwood', 'Wekiva Springs', 'Forest City', 'Ocoee area', 'Mt. Dora area'],
    description: 'Apopka is known as the Indoor Foliage Capital of the World and one of the fastest-growing cities in Orange County. We serve all of Apopka, Zellwood, Wekiva Springs, and northwest Orange County.',
  },
]

export function getCityBySlug(slug: string): City | undefined {
  return CITIES.find(c => c.slug === slug)
}
